"""
Neural Workflow Engine — Tools Registry
272 AI-powered tools across 19 categories.
"""

TOOL_CATEGORIES = [
    {
        "name": "Communication",
        "emoji": "📧",
        "tools": [
            {"name": "email.draft", "description": "Draft professional emails"},
            {"name": "email.sequence", "description": "Create multi-step email drip campaigns"},
            {"name": "email.template", "description": "Design reusable email templates"},
            {"name": "email.followup", "description": "Generate follow-up email sequences"},
            {"name": "email.cold_outreach", "description": "Craft cold outreach emails"},
            {"name": "email.newsletter", "description": "Write email newsletter editions"},
            {"name": "slack.compose", "description": "Draft Slack messages and announcements"},
            {"name": "slack.workflow", "description": "Design Slack automation workflows"},
            {"name": "slack.bot_config", "description": "Configure Slack bot responses"},
            {"name": "sms.draft", "description": "Draft SMS/text message campaigns"},
            {"name": "sms.campaign", "description": "Plan multi-message SMS campaigns"},
            {"name": "meeting.agenda", "description": "Create structured meeting agendas"},
            {"name": "meeting.notes", "description": "Generate meeting summaries and action items"},
            {"name": "meeting.scheduler", "description": "Optimize meeting scheduling"},
            {"name": "meeting.followup", "description": "Draft post-meeting follow-ups"},
            {"name": "voicemail.script", "description": "Write professional voicemail scripts"},
        ],
    },
    {
        "name": "Development",
        "emoji": "💻",
        "tools": [
            {"name": "code.generate", "description": "Write production-ready code in any language"},
            {"name": "code.review", "description": "Review code and suggest improvements"},
            {"name": "code.debug", "description": "Analyze and fix code bugs"},
            {"name": "code.refactor", "description": "Refactor code for better structure"},
            {"name": "code.optimize", "description": "Optimize code for performance"},
            {"name": "code.test", "description": "Generate unit and integration tests"},
            {"name": "code.document", "description": "Generate code documentation and comments"},
            {"name": "code.api_design", "description": "Design REST/GraphQL API schemas"},
            {"name": "code.database_schema", "description": "Design database schemas and models"},
            {"name": "code.migration", "description": "Write database migration scripts"},
            {"name": "github.pr_description", "description": "Write detailed PR descriptions"},
            {"name": "github.issue_template", "description": "Create GitHub issue templates"},
            {"name": "github.readme", "description": "Generate comprehensive README files"},
            {"name": "github.actions", "description": "Create GitHub Actions workflows"},
            {"name": "github.release_notes", "description": "Write release notes and changelogs"},
            {"name": "devops.dockerfile", "description": "Generate Dockerfiles and compose configs"},
            {"name": "devops.kubernetes", "description": "Write Kubernetes manifests and Helm charts"},
            {"name": "devops.terraform", "description": "Create Terraform infrastructure configs"},
            {"name": "devops.ci_cd", "description": "Design CI/CD pipeline configurations"},
            {"name": "devops.script", "description": "Write deployment and automation scripts"},
            {"name": "devops.monitoring", "description": "Set up monitoring and alerting configs"},
            {"name": "architecture.diagram", "description": "Create system architecture diagrams"},
            {"name": "architecture.decision", "description": "Write Architecture Decision Records"},
            {"name": "architecture.microservices", "description": "Design microservices architecture"},
        ],
    },
    {
        "name": "Documents",
        "emoji": "📄",
        "tools": [
            {"name": "doc.proposal", "description": "Create business proposals and pitches"},
            {"name": "doc.sop", "description": "Write Standard Operating Procedures"},
            {"name": "doc.report", "description": "Generate detailed reports with analysis"},
            {"name": "doc.contract", "description": "Draft contracts and agreements"},
            {"name": "doc.invoice", "description": "Generate professional invoices"},
            {"name": "doc.presentation", "description": "Create presentation outlines and slides"},
            {"name": "doc.readme", "description": "Write project README documentation"},
            {"name": "doc.policy", "description": "Draft company policies"},
            {"name": "doc.memo", "description": "Write internal memos and communications"},
            {"name": "doc.whitepaper", "description": "Create technical whitepapers"},
            {"name": "doc.case_study", "description": "Write customer case studies"},
            {"name": "doc.minutes", "description": "Generate meeting minutes"},
            {"name": "doc.handbook", "description": "Create employee or user handbooks"},
            {"name": "doc.rfp", "description": "Write Request for Proposals"},
            {"name": "doc.specification", "description": "Create technical specifications"},
            {"name": "doc.user_guide", "description": "Write user guides and manuals"},
            {"name": "doc.changelog", "description": "Generate product changelogs"},
            {"name": "doc.faq", "description": "Create FAQ documents"},
        ],
    },
    {
        "name": "Analytics & Research",
        "emoji": "📊",
        "tools": [
            {"name": "analytics.competitor", "description": "Analyze competitor landscape"},
            {"name": "analytics.market", "description": "Research market size and opportunities"},
            {"name": "analytics.seo", "description": "SEO audit and keyword strategy"},
            {"name": "analytics.pricing", "description": "Pricing strategy analysis"},
            {"name": "analytics.funnel", "description": "Sales funnel analysis and optimization"},
            {"name": "analytics.cohort", "description": "Cohort analysis and segmentation"},
            {"name": "analytics.retention", "description": "User retention analysis"},
            {"name": "analytics.churn", "description": "Churn prediction and prevention"},
            {"name": "analytics.roi", "description": "ROI calculation and analysis"},
            {"name": "analytics.benchmark", "description": "Industry benchmarking reports"},
            {"name": "research.topic", "description": "Deep research on any topic"},
            {"name": "research.trends", "description": "Industry trend analysis and predictions"},
            {"name": "research.survey", "description": "Design surveys and questionnaires"},
            {"name": "research.user_persona", "description": "Create detailed user personas"},
            {"name": "research.swot", "description": "SWOT analysis generation"},
            {"name": "research.industry", "description": "Industry landscape reports"},
        ],
    },
    {
        "name": "Marketing & Content",
        "emoji": "✍️",
        "tools": [
            {"name": "content.blog", "description": "Write SEO-optimized blog posts"},
            {"name": "content.social", "description": "Create social media post batches"},
            {"name": "content.ad_copy", "description": "Write ad copy for all platforms"},
            {"name": "content.landing_page", "description": "Write landing page copy with CTAs"},
            {"name": "content.newsletter", "description": "Draft email newsletter content"},
            {"name": "content.video_script", "description": "Write video scripts"},
            {"name": "content.case_study", "description": "Write customer success stories"},
            {"name": "content.press_release", "description": "Draft press releases"},
            {"name": "content.webinar", "description": "Create webinar scripts and outlines"},
            {"name": "content.podcast_outline", "description": "Plan podcast episodes"},
            {"name": "content.infographic", "description": "Design infographic content and data"},
            {"name": "content.whitepaper", "description": "Write marketing whitepapers"},
            {"name": "content.ebook", "description": "Outline and draft ebooks"},
            {"name": "branding.name", "description": "Generate brand/product name ideas"},
            {"name": "branding.tagline", "description": "Create taglines and value propositions"},
            {"name": "branding.voice", "description": "Define brand voice and tone"},
            {"name": "branding.guidelines", "description": "Create brand guideline documents"},
            {"name": "branding.story", "description": "Craft brand origin stories"},
            {"name": "marketing.strategy", "description": "Create marketing strategies"},
            {"name": "marketing.campaign", "description": "Plan marketing campaigns"},
            {"name": "marketing.ab_test", "description": "Design A/B test experiments"},
            {"name": "marketing.persona", "description": "Create marketing personas"},
        ],
    },
    {
        "name": "Planning & PM",
        "emoji": "📅",
        "tools": [
            {"name": "plan.roadmap", "description": "Create product or project roadmaps"},
            {"name": "plan.sprint", "description": "Plan sprint cycles with user stories"},
            {"name": "plan.launch", "description": "Create product launch checklists"},
            {"name": "plan.timeline", "description": "Build project timelines with milestones"},
            {"name": "plan.quarterly", "description": "Quarterly planning and goal setting"},
            {"name": "plan.annual", "description": "Annual strategic planning"},
            {"name": "plan.retrospective", "description": "Create sprint retrospective templates"},
            {"name": "plan.risk_assessment", "description": "Risk assessment and mitigation plans"},
            {"name": "task.breakdown", "description": "Break complex projects into tasks"},
            {"name": "task.prioritize", "description": "Prioritize with ICE/RICE/MoSCoW"},
            {"name": "task.estimate", "description": "Estimate task effort and timelines"},
            {"name": "task.delegate", "description": "Create delegation plans"},
            {"name": "project.status_report", "description": "Generate project status reports"},
            {"name": "project.kickoff", "description": "Create project kickoff documents"},
        ],
    },
    {
        "name": "Finance & Business",
        "emoji": "💰",
        "tools": [
            {"name": "finance.forecast", "description": "Create financial forecasts"},
            {"name": "finance.budget", "description": "Draft budget plans and allocation"},
            {"name": "finance.invoice", "description": "Generate detailed invoices"},
            {"name": "finance.expense_report", "description": "Create expense reports"},
            {"name": "finance.pitch_deck", "description": "Create pitch deck content"},
            {"name": "finance.financial_model", "description": "Build financial models"},
            {"name": "finance.unit_economics", "description": "Calculate unit economics"},
            {"name": "finance.pricing_strategy", "description": "Develop pricing strategies"},
            {"name": "finance.revenue_model", "description": "Design revenue models"},
            {"name": "finance.cap_table", "description": "Create cap table structures"},
            {"name": "business.plan", "description": "Write comprehensive business plans"},
            {"name": "business.model_canvas", "description": "Create Business Model Canvas"},
            {"name": "business.okrs", "description": "Define OKRs and key results"},
            {"name": "business.kpi_dashboard", "description": "Design KPI dashboards"},
        ],
    },
    {
        "name": "Design & Creative",
        "emoji": "🎨",
        "tools": [
            {"name": "design.wireframe", "description": "Create wireframe descriptions"},
            {"name": "design.system", "description": "Design component systems"},
            {"name": "design.prompt", "description": "Generate AI image prompts"},
            {"name": "design.mockup", "description": "Describe detailed UI mockups"},
            {"name": "design.prototype", "description": "Plan interactive prototypes"},
            {"name": "design.user_flow", "description": "Map user flows and journeys"},
            {"name": "design.sitemap", "description": "Create website sitemaps"},
            {"name": "design.color_palette", "description": "Generate color palettes"},
            {"name": "design.typography", "description": "Select typography pairings"},
            {"name": "design.icon_set", "description": "Design icon set specifications"},
            {"name": "design.brand_kit", "description": "Create brand identity kits"},
            {"name": "design.banner", "description": "Design banner ad specifications"},
            {"name": "design.email_template", "description": "Design HTML email templates"},
            {"name": "design.social_template", "description": "Create social media templates"},
        ],
    },
    {
        "name": "HR & Operations",
        "emoji": "👥",
        "tools": [
            {"name": "hr.job_posting", "description": "Write job descriptions and postings"},
            {"name": "hr.interview", "description": "Create interview question sets"},
            {"name": "hr.onboarding", "description": "Design employee onboarding checklists"},
            {"name": "hr.offboarding", "description": "Create offboarding procedures"},
            {"name": "hr.performance_review", "description": "Write performance review templates"},
            {"name": "hr.compensation", "description": "Create compensation analysis"},
            {"name": "hr.culture_doc", "description": "Write company culture documents"},
            {"name": "hr.diversity_plan", "description": "Create diversity and inclusion plans"},
            {"name": "ops.process", "description": "Map and optimize business processes"},
            {"name": "ops.workflow", "description": "Design operational workflows"},
            {"name": "ops.inventory", "description": "Create inventory management plans"},
            {"name": "ops.supply_chain", "description": "Optimize supply chain operations"},
            {"name": "ops.vendor_eval", "description": "Create vendor evaluation frameworks"},
            {"name": "ops.quality_check", "description": "Design quality assurance checklists"},
        ],
    },
    {
        "name": "Sales & CRM",
        "emoji": "📈",
        "tools": [
            {"name": "sales.pitch", "description": "Create sales pitch scripts"},
            {"name": "sales.proposal", "description": "Write sales proposals"},
            {"name": "sales.objection_handler", "description": "Create objection handling guides"},
            {"name": "sales.follow_up", "description": "Draft sales follow-up sequences"},
            {"name": "sales.cold_call_script", "description": "Write cold call scripts"},
            {"name": "sales.demo_script", "description": "Create product demo scripts"},
            {"name": "sales.pricing_quote", "description": "Generate pricing quotes"},
            {"name": "sales.battlecard", "description": "Create competitive battlecards"},
            {"name": "sales.territory_plan", "description": "Design territory plans"},
            {"name": "crm.email_sequence", "description": "Build CRM email sequences"},
            {"name": "crm.lead_scoring", "description": "Create lead scoring models"},
            {"name": "crm.pipeline_report", "description": "Generate pipeline reports"},
            {"name": "crm.win_loss_analysis", "description": "Analyze win/loss patterns"},
            {"name": "crm.customer_profile", "description": "Build ideal customer profiles"},
        ],
    },
    {
        "name": "Legal & Compliance",
        "emoji": "⚖️",
        "tools": [
            {"name": "legal.terms_of_service", "description": "Draft Terms of Service"},
            {"name": "legal.privacy_policy", "description": "Create privacy policies"},
            {"name": "legal.nda", "description": "Draft Non-Disclosure Agreements"},
            {"name": "legal.employment_contract", "description": "Create employment contracts"},
            {"name": "legal.contractor_agreement", "description": "Draft contractor agreements"},
            {"name": "legal.ip_assignment", "description": "Create IP assignment documents"},
            {"name": "legal.gdpr_audit", "description": "Perform GDPR compliance audits"},
            {"name": "legal.cookie_policy", "description": "Draft cookie policies"},
            {"name": "compliance.checklist", "description": "Create compliance checklists"},
            {"name": "compliance.risk_register", "description": "Build risk registers"},
            {"name": "compliance.audit_report", "description": "Generate audit reports"},
            {"name": "compliance.incident_response", "description": "Create incident response plans"},
        ],
    },
    {
        "name": "Customer Support",
        "emoji": "🎧",
        "tools": [
            {"name": "support.knowledge_base", "description": "Create knowledge base articles"},
            {"name": "support.faq", "description": "Generate FAQ pages"},
            {"name": "support.canned_response", "description": "Write canned support responses"},
            {"name": "support.escalation_guide", "description": "Create escalation procedures"},
            {"name": "support.sla_policy", "description": "Define SLA policies"},
            {"name": "support.ticket_template", "description": "Design support ticket templates"},
            {"name": "support.chatbot_flow", "description": "Design chatbot conversation flows"},
            {"name": "support.onboarding_guide", "description": "Create customer onboarding guides"},
            {"name": "support.feedback_survey", "description": "Design feedback surveys"},
            {"name": "support.nps_survey", "description": "Create NPS survey campaigns"},
            {"name": "support.bug_report_template", "description": "Design bug report templates"},
            {"name": "support.root_cause_analysis", "description": "Perform root cause analyses"},
        ],
    },
    {
        "name": "Data & Database",
        "emoji": "🗄️",
        "tools": [
            {"name": "data.schema_design", "description": "Design database schemas"},
            {"name": "data.migration_script", "description": "Write data migration scripts"},
            {"name": "data.etl_pipeline", "description": "Design ETL pipeline configurations"},
            {"name": "data.query_optimize", "description": "Optimize SQL/NoSQL queries"},
            {"name": "data.backup_strategy", "description": "Create backup and recovery plans"},
            {"name": "data.visualization", "description": "Design data visualization specs"},
            {"name": "data.cleaning_script", "description": "Write data cleaning scripts"},
            {"name": "data.api_spec", "description": "Create OpenAPI/Swagger specifications"},
            {"name": "data.csv_transform", "description": "Transform and process CSV data"},
            {"name": "data.json_schema", "description": "Create JSON Schema definitions"},
            {"name": "data.report_builder", "description": "Design automated report builders"},
            {"name": "data.dashboard_config", "description": "Configure analytics dashboards"},
        ],
    },
    {
        "name": "Security",
        "emoji": "🔒",
        "tools": [
            {"name": "security.audit", "description": "Perform security audit assessments"},
            {"name": "security.penetration_test", "description": "Plan penetration test scenarios"},
            {"name": "security.threat_model", "description": "Create threat models"},
            {"name": "security.incident_plan", "description": "Write incident response plans"},
            {"name": "security.access_control", "description": "Design access control policies"},
            {"name": "security.encryption_guide", "description": "Create encryption implementation guides"},
            {"name": "security.vulnerability_report", "description": "Generate vulnerability reports"},
            {"name": "security.security_policy", "description": "Write security policies"},
            {"name": "security.backup_plan", "description": "Create backup and disaster plans"},
            {"name": "security.disaster_recovery", "description": "Design disaster recovery procedures"},
        ],
    },
    {
        "name": "Education & Training",
        "emoji": "🎓",
        "tools": [
            {"name": "training.course_outline", "description": "Create course outlines"},
            {"name": "training.lesson_plan", "description": "Design lesson plans"},
            {"name": "training.quiz", "description": "Generate quizzes and assessments"},
            {"name": "training.certification", "description": "Design certification programs"},
            {"name": "training.workshop", "description": "Plan workshop sessions"},
            {"name": "training.tutorial", "description": "Write step-by-step tutorials"},
            {"name": "training.documentation", "description": "Create training documentation"},
            {"name": "training.assessment", "description": "Design skill assessments"},
            {"name": "training.mentorship_plan", "description": "Create mentorship programs"},
            {"name": "training.skill_matrix", "description": "Build skill matrix frameworks"},
        ],
    },
    {
        "name": "Social Media",
        "emoji": "📱",
        "tools": [
            {"name": "social.content_calendar", "description": "Create content calendars"},
            {"name": "social.post_linkedin", "description": "Write LinkedIn posts and articles"},
            {"name": "social.post_twitter", "description": "Craft tweets and Twitter threads"},
            {"name": "social.post_instagram", "description": "Write Instagram captions and stories"},
            {"name": "social.post_tiktok", "description": "Create TikTok video concepts"},
            {"name": "social.hashtag_strategy", "description": "Develop hashtag strategies"},
            {"name": "social.influencer_brief", "description": "Write influencer collaboration briefs"},
            {"name": "social.community_guidelines", "description": "Create community guidelines"},
            {"name": "social.engagement_report", "description": "Generate engagement reports"},
            {"name": "social.crisis_response", "description": "Create social media crisis plans"},
        ],
    },
    {
        "name": "E-commerce",
        "emoji": "🛒",
        "tools": [
            {"name": "ecommerce.product_description", "description": "Write product descriptions"},
            {"name": "ecommerce.category_page", "description": "Create category page content"},
            {"name": "ecommerce.email_campaign", "description": "Design e-commerce email campaigns"},
            {"name": "ecommerce.abandoned_cart", "description": "Write abandoned cart recovery emails"},
            {"name": "ecommerce.upsell_strategy", "description": "Create upsell/cross-sell strategies"},
            {"name": "ecommerce.review_response", "description": "Draft product review responses"},
            {"name": "ecommerce.shipping_policy", "description": "Write shipping and delivery policies"},
            {"name": "ecommerce.return_policy", "description": "Create return and refund policies"},
            {"name": "ecommerce.loyalty_program", "description": "Design loyalty and rewards programs"},
            {"name": "ecommerce.pricing_strategy", "description": "Develop e-commerce pricing strategies"},
        ],
    },
    {
        "name": "Automation",
        "emoji": "🔗",
        "tools": [
            {"name": "automation.workflow", "description": "Design automation workflows"},
            {"name": "automation.trigger", "description": "Configure event triggers and actions"},
            {"name": "automation.webhook", "description": "Set up webhook configurations"},
            {"name": "automation.api_integration", "description": "Design API integration plans"},
            {"name": "automation.zapier_config", "description": "Create Zapier automation recipes"},
            {"name": "automation.n8n_workflow", "description": "Build n8n workflow configurations"},
            {"name": "automation.cron_job", "description": "Schedule and configure cron jobs"},
            {"name": "automation.notification", "description": "Set up notification systems"},
            {"name": "automation.data_sync", "description": "Design data synchronization flows"},
            {"name": "automation.batch_process", "description": "Create batch processing scripts"},
        ],
    },
    {
        "name": "AI & ML",
        "emoji": "🤖",
        "tools": [
            {"name": "ai.prompt_engineer", "description": "Craft optimized AI prompts"},
            {"name": "ai.model_eval", "description": "Create model evaluation frameworks"},
            {"name": "ai.training_data", "description": "Generate training datasets"},
            {"name": "ai.chatbot_design", "description": "Design chatbot conversation flows"},
            {"name": "ai.recommendation", "description": "Build recommendation system logic"},
            {"name": "ai.classification", "description": "Design text classification systems"},
            {"name": "ai.sentiment_analysis", "description": "Create sentiment analysis pipelines"},
            {"name": "ai.summarization", "description": "Build text summarization systems"},
            {"name": "ai.translation", "description": "Create translation and localization"},
            {"name": "ai.image_generation", "description": "Generate AI image prompts and configs"},
        ],
    },
]


def get_all_tools_flat():
    """Return a flat list of all tools."""
    tools = []
    for cat in TOOL_CATEGORIES:
        for tool in cat["tools"]:
            tools.append({**tool, "category": cat["name"]})
    return tools


def get_tool_count():
    """Return total number of tools."""
    return sum(len(cat["tools"]) for cat in TOOL_CATEGORIES)


def get_planner_tool_summary():
    """Return a compact summary of tools for the planner prompt."""
    lines = []
    for cat in TOOL_CATEGORIES:
        emoji = cat["emoji"]
        name = cat["name"].upper()
        tool_names = [t["name"] for t in cat["tools"]]
        lines.append(f"{emoji} {name}:")
        for tn in tool_names:
            desc = next(t["description"] for t in cat["tools"] if t["name"] == tn)
            lines.append(f"- {tn}: {desc}")
        lines.append("")
    return "\n".join(lines)
